#include "STD_TYPES.h" 
#include "BIT_OP.h" 

#include "GPIO_Interface.h" 
#include "NVIC_interface.h" 
#include "EXTI_Interface.h"
#include "SYSTICK_Interface.h"
#include "DOTMATRIX_interface.h"
#include "DOTMATRIX_private.h"
#include "DOTMATRIX_config.h"



static uint8 * DATA_DISPLAY ; 
static uint8 INDEX_OF_DATA_DISPLAY = 0 ;

void DOTMATRIX_Init(void)
{
	
	vGPIO_PIN_Mode(DOT_Matrix_COLUMN_0,GPIO_OUTPUT_MODE);
	vGPIO_PIN_Mode(DOT_Matrix_COLUMN_1,GPIO_OUTPUT_MODE);
	vGPIO_PIN_Mode(DOT_Matrix_COLUMN_2,GPIO_OUTPUT_MODE);
	vGPIO_PIN_Mode(DOT_Matrix_COLUMN_3,GPIO_OUTPUT_MODE);
	vGPIO_PIN_Mode(DOT_Matrix_COLUMN_4,GPIO_OUTPUT_MODE);
	vGPIO_PIN_Mode(DOT_Matrix_COLUMN_5,GPIO_OUTPUT_MODE);
	vGPIO_PIN_Mode(DOT_Matrix_COLUMN_6,GPIO_OUTPUT_MODE);
	vGPIO_PIN_Mode(DOT_Matrix_COLUMN_7,GPIO_OUTPUT_MODE);

	vGPIO_OUTPUT_PIN_TYPE(DOT_Matrix_COLUMN_0,GPIO_OUTPUT_PUSHPULL);
	vGPIO_OUTPUT_PIN_TYPE(DOT_Matrix_COLUMN_1,GPIO_OUTPUT_PUSHPULL);
	vGPIO_OUTPUT_PIN_TYPE(DOT_Matrix_COLUMN_2,GPIO_OUTPUT_PUSHPULL);
	vGPIO_OUTPUT_PIN_TYPE(DOT_Matrix_COLUMN_3,GPIO_OUTPUT_PUSHPULL);
	vGPIO_OUTPUT_PIN_TYPE(DOT_Matrix_COLUMN_4,GPIO_OUTPUT_PUSHPULL);
	vGPIO_OUTPUT_PIN_TYPE(DOT_Matrix_COLUMN_5,GPIO_OUTPUT_PUSHPULL);
	vGPIO_OUTPUT_PIN_TYPE(DOT_Matrix_COLUMN_6,GPIO_OUTPUT_PUSHPULL);
	vGPIO_OUTPUT_PIN_TYPE(DOT_Matrix_COLUMN_7,GPIO_OUTPUT_PUSHPULL);
	
	
	vGPIO_OUTPUT_PIN_SPEED(DOT_Matrix_COLUMN_0,GPIO_OUTPUT_MEDIUM_SPEED);
	vGPIO_OUTPUT_PIN_SPEED(DOT_Matrix_COLUMN_1,GPIO_OUTPUT_MEDIUM_SPEED);
	vGPIO_OUTPUT_PIN_SPEED(DOT_Matrix_COLUMN_2,GPIO_OUTPUT_MEDIUM_SPEED);
	vGPIO_OUTPUT_PIN_SPEED(DOT_Matrix_COLUMN_3,GPIO_OUTPUT_MEDIUM_SPEED);
	vGPIO_OUTPUT_PIN_SPEED(DOT_Matrix_COLUMN_4,GPIO_OUTPUT_MEDIUM_SPEED);
	vGPIO_OUTPUT_PIN_SPEED(DOT_Matrix_COLUMN_5,GPIO_OUTPUT_MEDIUM_SPEED);
	vGPIO_OUTPUT_PIN_SPEED(DOT_Matrix_COLUMN_6,GPIO_OUTPUT_MEDIUM_SPEED);
	



	
	vGPIO_PIN_Mode(DOT_Matrix_ROW_0,GPIO_OUTPUT_MODE);
	vGPIO_PIN_Mode(DOT_Matrix_ROW_1,GPIO_OUTPUT_MODE);
	vGPIO_PIN_Mode(DOT_Matrix_ROW_2,GPIO_OUTPUT_MODE);
	vGPIO_PIN_Mode(DOT_Matrix_ROW_3,GPIO_OUTPUT_MODE);
	vGPIO_PIN_Mode(DOT_Matrix_ROW_4,GPIO_OUTPUT_MODE);
	vGPIO_PIN_Mode(DOT_Matrix_ROW_5,GPIO_OUTPUT_MODE);
	vGPIO_PIN_Mode(DOT_Matrix_ROW_6,GPIO_OUTPUT_MODE);
	vGPIO_PIN_Mode(DOT_Matrix_ROW_7,GPIO_OUTPUT_MODE);

	vGPIO_OUTPUT_PIN_TYPE(DOT_Matrix_ROW_0,GPIO_OUTPUT_PUSHPULL);
	vGPIO_OUTPUT_PIN_TYPE(DOT_Matrix_ROW_1,GPIO_OUTPUT_PUSHPULL);
	vGPIO_OUTPUT_PIN_TYPE(DOT_Matrix_ROW_2,GPIO_OUTPUT_PUSHPULL);
	vGPIO_OUTPUT_PIN_TYPE(DOT_Matrix_ROW_3,GPIO_OUTPUT_PUSHPULL);
	vGPIO_OUTPUT_PIN_TYPE(DOT_Matrix_ROW_4,GPIO_OUTPUT_PUSHPULL);
	vGPIO_OUTPUT_PIN_TYPE(DOT_Matrix_ROW_5,GPIO_OUTPUT_PUSHPULL);
	vGPIO_OUTPUT_PIN_TYPE(DOT_Matrix_ROW_6,GPIO_OUTPUT_PUSHPULL);
	vGPIO_OUTPUT_PIN_TYPE(DOT_Matrix_ROW_7,GPIO_OUTPUT_PUSHPULL);
	
	
	vGPIO_OUTPUT_PIN_SPEED(DOT_Matrix_ROW_0,GPIO_OUTPUT_MEDIUM_SPEED);
	vGPIO_OUTPUT_PIN_SPEED(DOT_Matrix_ROW_1,GPIO_OUTPUT_MEDIUM_SPEED);
	vGPIO_OUTPUT_PIN_SPEED(DOT_Matrix_ROW_2,GPIO_OUTPUT_MEDIUM_SPEED);
	vGPIO_OUTPUT_PIN_SPEED(DOT_Matrix_ROW_3,GPIO_OUTPUT_MEDIUM_SPEED);
	vGPIO_OUTPUT_PIN_SPEED(DOT_Matrix_ROW_4,GPIO_OUTPUT_MEDIUM_SPEED);
	vGPIO_OUTPUT_PIN_SPEED(DOT_Matrix_ROW_5,GPIO_OUTPUT_MEDIUM_SPEED);
	vGPIO_OUTPUT_PIN_SPEED(DOT_Matrix_ROW_6,GPIO_OUTPUT_MEDIUM_SPEED);
	

}


void DOTMATRIX_Display(uint8 * DATA ){
	
	
		DATA_DISPLAY = DATA ; 
		
		INDEX_OF_DATA_DISPLAY = 0 ; 
	
		Active_column(INDEX_OF_DATA_DISPLAY); 
		
		DOTMATRIX_SetRaw_value(DATA[INDEX_OF_DATA_DISPLAY]);
		SYS_voidTick_IntervalPeriodic(2500,DOTMATRIX_Next_column);
	
}






void DOTMATRIX_Next_column(void)
{
	
	INDEX_OF_DATA_DISPLAY++ ;
	if(INDEX_OF_DATA_DISPLAY == 8 )
	{
		INDEX_OF_DATA_DISPLAY =0 ;
	}
		
	Active_column(INDEX_OF_DATA_DISPLAY);
	DOTMATRIX_SetRaw_value(DATA_DISPLAY[INDEX_OF_DATA_DISPLAY]);
	
}

void Active_column(uint8 column)
{
	
	vGPIO_Write_PIN(DOT_Matrix_COLUMN_0,HIGH);
	vGPIO_Write_PIN(DOT_Matrix_COLUMN_1,HIGH);
	vGPIO_Write_PIN(DOT_Matrix_COLUMN_2,HIGH);
	vGPIO_Write_PIN(DOT_Matrix_COLUMN_3,HIGH);
	vGPIO_Write_PIN(DOT_Matrix_COLUMN_4,HIGH);
	vGPIO_Write_PIN(DOT_Matrix_COLUMN_5,HIGH);
	vGPIO_Write_PIN(DOT_Matrix_COLUMN_6,HIGH);
	vGPIO_Write_PIN(DOT_Matrix_COLUMN_7,HIGH);
	

	switch(column)
{
	
		case 0 : 
			vGPIO_Write_PIN(DOT_Matrix_COLUMN_0,LOW);
		break;
		case 1 : 
			vGPIO_Write_PIN(DOT_Matrix_COLUMN_1,LOW);
		break; 
		case 2 : 
			vGPIO_Write_PIN(DOT_Matrix_COLUMN_2,LOW);
		break;
		case 3 : 
			vGPIO_Write_PIN(DOT_Matrix_COLUMN_3,LOW);
		break;
		case 4 : 
			vGPIO_Write_PIN(DOT_Matrix_COLUMN_4,LOW);
		break;
		case 5 : 
			vGPIO_Write_PIN(DOT_Matrix_COLUMN_5,LOW);
		break;
		case 6 : 
			vGPIO_Write_PIN(DOT_Matrix_COLUMN_6,LOW);
		break;
		case 7 : 
			vGPIO_Write_PIN(DOT_Matrix_COLUMN_7,LOW);
		break;
}

}



void DOTMATRIX_SetRaw_value(uint8 Value){
	
	uint8 LOCAL_Index ; 
	uint8 LOCAL_Value[8];
	
 	for(LOCAL_Index =0 ; LOCAL_Index <= 8 ; LOCAL_Index++)
	{
		LOCAL_Value[LOCAL_Index] = Get_Bit(Value,LOCAL_Index);
	}
 	
	
	vGPIO_Write_PIN(DOT_Matrix_ROW_0 ,LOCAL_Value[0]);
	vGPIO_Write_PIN(DOT_Matrix_ROW_1 ,LOCAL_Value[1]);
	vGPIO_Write_PIN(DOT_Matrix_ROW_2 ,LOCAL_Value[2]);
	vGPIO_Write_PIN(DOT_Matrix_ROW_3 ,LOCAL_Value[3]);
	vGPIO_Write_PIN(DOT_Matrix_ROW_4 ,LOCAL_Value[4]);
	vGPIO_Write_PIN(DOT_Matrix_ROW_5 ,LOCAL_Value[5]);
	vGPIO_Write_PIN(DOT_Matrix_ROW_6 ,LOCAL_Value[6]);
	vGPIO_Write_PIN(DOT_Matrix_ROW_7 ,LOCAL_Value[7]);

}
